tap "homebrew/bundle"
tap "homebrew/services"
brew "openssl@3"
brew "xz"
brew "cmake"
brew "gh"
brew "git"
brew "little-cms2"
brew "webp"
brew "mas"
brew "nvm"
brew "poppler"
brew "postgresql@14", restart_service: :changed
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.12"
brew "rust"
brew "stow"
brew "tcl-tk"
brew "tesseract"
brew "tesseract-lang"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "zlib"
cask "dbeaver-community"
cask "pgadmin4"
cask "postman"
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
vscode "batisteo.vscode-django"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dracula-theme.theme-dracula"
vscode "formulahendry.code-runner"
vscode "kevinrose.vsc-python-indent"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "njpwerner.autodocstring"
vscode "thiscodeworks.savecode"
vscode "twxs.cmake"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "wholroyd.jinja"
